---
- name: My test playbook
  hosts: all 
  become: yes
  
  tasks:
  - name: This is to copy a file
    copy:
      src: /home/ansiadmin/index.html
      dest: /home/ansiadmin/
      owner: ansiadmin 
      group: ansiadmin
      mode: 0644      




 
