---
#tasks file for setup-goal-roal
- name: Installing httpd
  yum:
    name: httpd
    state: installed
  when: ansible_os_family == "RedHat"
  notify: starting httpd 

- name: Installing apache2
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"
  notify: starting apache2


- name: Copy index.html
  copy:
    src: /home/ansiadmin/index.html
    dest: /var/www/html
    mode: 0666    
